# This is a basic workflow to help you get started with Actions

name: Copy and Move

on:
  push:

jobs:
  copy-file:
    runs-on: ubuntu-latest
    env:
      API_TOKEN_GITHUB: ${{ secrets.DEVELOPER_DOCS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push Folder Content
        uses: dmnemec/copy_file_to_another_repo_action@main
        with:
          source_file: 'docs/index.md'
          destination_branch: 'master'
          destination_repo: 'bcc-code/bcc-code.github.io'
          destination_folder: '_projects/bcc-wp'
          user_email: 'bcc-docs-bot@bcc.no'
          user_name: 'bcc-docs-bot'
          commit_message: 'Update Wordpress Project Docs'

      - name: Push Folder Content
        uses: dmnemec/copy_file_to_another_repo_action@main
        with:
          source_file: 'docs/signon/.'
          destination_branch: 'master'
          destination_repo: 'bcc-code/bcc-code.github.io'
          destination_folder: '_projects/bcc-wp/signon'
          user_email: 'bcc-docs-bot@bcc.no'
          user_name: 'bcc-docs-bot'
          commit_message: 'Update Wordpress Project Docs'

      - name: Push Folder Content
        uses: dmnemec/copy_file_to_another_repo_action@main
        with:
          source_file: 'docs/api/.'
          destination_branch: 'master'
          destination_repo: 'bcc-code/bcc-code.github.io'
          destination_folder: '_apis'
          user_email: 'bcc-docs-bot@bcc.no'
          user_name: 'bcc-docs-bot'
          commit_message: 'Update Wordpress Project Docs'
